language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy

env:
  - BACKEND=c
  - BACKEND=cpp

branches:
  only:
    - master

before_install:
  - sudo apt-get update
  - sudo apt-get install gdb python$( python -c 'import sys; print("%d.%d" % sys.version_info[:2])' )-dbg || true
  - dpkg -l | grep gdb || true

install: CFLAGS="-O2 -ggdb" pip install .

script:
  - PYTHON_DBG="python$( python -c 'import sys; print("%d.%d" % sys.version_info[:2])' )-dbg"
  - if $PYTHON_DBG -V >&2; then CFLAGS="-O0 -ggdb" $PYTHON_DBG runtests.py -vv Debugger --backends=$BACKEND; fi
  - CFLAGS="-O0 -ggdb" python runtests.py -vv -x Debugger --backends=$BACKEND

matrix:
  allow_failures:
    - python: pypy
  fast_finish: true
