language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

#  - pypy

branches:
  only:
    - master

before_install:
  - sudo apt-get update
  - sudo apt-get install gdb python$((python -c 'import sys; print("%d.%d" % sys.version_info[:2])'))-dbg || true
  - dpkg -l | grep gdb || true

install: pip install .

script:
  - PYTHON="`python$((python -c 'import sys; print("%d.%d" % sys.version_info[:2])'))-dbg`"
  - CFLAGS="-O0 -ggdb" $(($PYTHON -V >&2 && echo $PYTHON || echo python)) runtests.py -vv

matrix:
  allow_failures:
    - python: pypy
